/* empty css                      */import{a as q,S as E,i as a}from"./assets/vendor-C4-ZuMk8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const S="https://pixabay.com/api/",I="47083807-1148cb0c408c5877c55e45261",h=async(t,r=1,l=15)=>{const s={key:I,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:l};try{return(await q.get(S,{params:s})).data}catch{throw new Error("Failed to fetch images")}};let y;const p=t=>{const r=document.querySelector(".gallery"),l=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:c,views:L,comments:v,downloads:w})=>`<a class="gallery__item" href="${e}">
          <div class="photo-card">
            <img src="${s}" alt="${o}" loading="lazy" />
            <div class="info">
              <p class="info-item"><b>Likes</b>: ${c}</p>
              <p class="info-item"><b>Views</b>: ${L}</p>
              <p class="info-item"><b>Comments</b>: ${v}</p>
              <p class="info-item"><b>Downloads</b>: ${w}</p>
            </div>
          </div>
        </a>`).join("");r.insertAdjacentHTML("beforeend",l),y?y.refresh():y=new E(".gallery a")},P=()=>{const t=document.querySelector(".gallery");t.innerHTML=""},g=document.querySelector("#search-form"),m=document.querySelector(".load-more"),n=document.querySelector(".loader");let d="",i=1;const u=15;let f=0;const b=t=>t.classList.add("hidden"),$=t=>t.classList.remove("hidden"),O=async t=>{if(t.preventDefault(),d=g.elements.searchQuery.value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search query!"});return}P(),i=1,b(m);try{n.style.display="block";const r=await h(d,i,u);if(n.style.display="none",r.hits.length===0){a.info({title:"Info",message:"No images found. Try another query."});return}p(r.hits),f=r.totalHits,i*u<f?$(m):a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(r){n.style.display="none",a.error({title:"Error",message:r.message})}},_=async()=>{i+=1;try{n.style.display="block";const t=await h(d,i,u);n.style.display="none",p(t.hits),i*u>=f&&(b(m),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch(t){n.style.display="none",a.error({title:"Error",message:t.message})}};g.addEventListener("submit",O);m.addEventListener("click",_);
//# sourceMappingURL=index.js.map
